"""'initial'

Revision ID: 30aa2409a86e
Revises: 765624e6c28a
Create Date: 2024-08-31 20:24:51.078867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30aa2409a86e'
down_revision: Union[str, None] = '765624e6c28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_swipes_id', table_name='swipes')
    op.drop_table('swipes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name='swipes_target_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='swipes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='swipes_pkey')
    )
    op.create_index('ix_swipes_id', 'swipes', ['id'], unique=False)
    # ### end Alembic commands ###
